### PR TITLE
[React Package] - Configuring Package.json and build commands

### PR DESCRIPTION
**Pull request by vinayaksh42**
- Configuring Package.json and build commands for publishing the package to npm. 
Addition of GitHub workflow for semantic versioning
- Setting up semantic versioning according to the conventions used in EOS.

I have added semantic versioning but it won't work until `NPM_TOKEN` is added as a secret in this repo. Upon addition of `NPM_TOKEN`, The package will be ready to be published for further testing.
This change requires to run `npm i`

### CODE REVIEW

**Comment by kaybhutani** [comment]
@en3sis can you configure the env variables please?

**Comment by en3sis** [comment]
@kbhutani0001 @vinayaksh42 `NPM_TOKEN` is added under my profile, I'll have it move to the org later.

Is there any extra configuration needed?

**Comment by kaybhutani** [comment]
Thats all i guess. @vinayaksh42 ?

**Comment by vinayaksh42** [comment]
> @kbhutani0001 @vinayaksh42 `NPM_TOKEN` is added under my profile, I'll have it move to the org later.
> 
> Is there any extra configuration needed?

No, that's everything that will be required for publishing it to npm for testing. The github token gets picked up automatically so it won't be required.

**Comment by en3sis** [comment]
can we merge this @kbhutani0001 ?

**Comment by kaybhutani** [comment]
Yes @en3sis sure. I thought we had to configure the tokens first

**Pull request merged**
